header: "&6&lHyper&f&lCloud&6&lMC &7&l>"
config:
   Database:
      allowJoinOnNoConnect: true
      server: jdbc:mysql://192.168.0.33:3306/HyperPrison
      user: java.prison
      password: mqJz6W5qT9
      databaseName: HyperPrison
      tableName: PlayerData
      columns:
#Valid Placeholders, for any suggestions please use the spigot post or email Admin@ElmHoe.co.uk if you want more added.
#{Player} will be replaced with the players name.
#{Amount} will be replaced with the amount.
Messages:
    withdrawal: " &6&oYou've withdrawn &a&l${Amount} &6&oSuccessfully."
    deposit: " &6&oYou've deposited &a&l${Amount} &6&oSuccessfully."
    insufficientFunds: " &4&l{Player} You've got insufficient funds."