name: HyperPrison
main: uk.co.ElmHoe.Prison.HyperPrison
version: 0.1
author: ElmHoe
load: POSTWORLD
depend: [Vault]
commands:
   ranks:
      description: This will list all prison ranks from DB
      usage: /<command> [args]